package com.example.mp3player

const val MEDIA_PLAYER_PLAY = "MEDIA_PLAYER_PLAY"
const val MEDIA_PLAYER_STOP = "MEDIA_PLAYER_STOP"
const val MEDIA_PLAYER_PAUSE = "MEDIA_PLAYER_PAUSE"
const val CHANNEL_ID = "MEDIA_PLAYER_CHANNEL"